
# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: The Gift Ticket

url: https://thegiftticket.com/

twitter:
  username: thegiftticket

facebook:
  app_id: 994582807295629
#  publisher: 956469971073545 <-throws errors in facebook when using on a "website" object
# You can use EITHER the fb:app_id or fb:admins, but not both.


# seems that this plugin picks up other .html files under bower components
#gems:
#  - jekyll-sitemap

gems:
  - jekyll-seo-tag