
# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: The Gift Ticket

url: http://thegiftticket.com/

twitter:
  username: thegiftticket

# seems that this plugin picks up other .html files under bower components
#gems:
#  - jekyll-sitemap

gems:
  - jekyll-seo-tag